### ISSUE TITLE
Cannot add secret named: student_id_pwd

### ISSUE THREAD

**Issue by CaiZhuoyue** [AutoRip/AutoReport#2]
I followed the README and tried to add secret 'student_id_pwd' in my forked repo settings but I got this error message saying that the name 'student_id_pwd' is invalid.

Why is that?

**Comment by AutoRip** [comment]
Hi there, I'm not quite sure if I got it right, it seems that the parser of Action yml file can not find those secrets you defined. Could you please check if there's any spelling mistakes in your input of secret name?

**Comment by CaiZhuoyue** [comment]
> Hi @CaiZhuoyue, I'm not quite sure if I got it right, it seems that the parser of Action yml file can not find those secrets you defined. Could you please check if there's any spelling mistakes in your input of secret name?

I checked and I'm pretty sure it's `STUDENT_ID` and `STUDENT_ID_PWD`. (Just so we are clear, it's "repository secrets" and "not environment secrets", right?)

**Comment by AutoRip** [comment]
Yes, what I refer to is repository secrets and they are two different secret items used in Action yml file, which means two secrets need adding to your forked repo. 

I've read your issue twice and then found that it's a secrets adding issue, not a parsing issue. lol. I want to ask that did you try not copy these strings but type them manually? As none of my friends have problem in adding these params, I think you may paste the string with characters that not allowed by github's rules, e.g. spaces. If manual input does not work, it's ok to use other secret names instead. Please be aware that you should replace secrets with the new ones in Action files! [Here](https://docs.github.com/en/actions/reference/encrypted-secrets) you can find detailed secrets using guide. :-)

**Comment by CaiZhuoyue** [comment]
> Yes, what I refer to is repository secrets and they are two different secret items used in Action yml file, which means two secrets need adding to your forked repo.
> 
> I've read your issue twice and then found that it's a secrets adding issue, not a parsing issue. lol. I want to ask that did you try not copy these strings but type them manually? As none of my friends have problem in adding these params, I think you may paste the string with characters that not allowed by github's rules, e.g. spaces. If manual input does not work, it's ok to use other secret names instead. Please be aware that you should replace secrets with the new ones in Action files! [Here](https://docs.github.com/en/actions/reference/encrypted-secrets) you can find detailed secrets using guide. :-)

Thanks for replying!
I deleted the older secrets and manually typed `student_id` and `student_id_pwd`. And I set the `student_id` as my student number:18120482 and `student_id_pwd` is my password for logging in the `shu.selfreport` website.

Should everything be alright now?

**Comment by AutoRip** [comment]
> > Yes, what I refer to is repository secrets and they are two different secret items used in Action yml file, which means two secrets need adding to your forked repo.
> > I've read your issue twice and then found that it's a secrets adding issue, not a parsing issue. lol. I want to ask that did you try not copy these strings but type them manually? As none of my friends have problem in adding these params, I think you may paste the string with characters that not allowed by github's rules, e.g. spaces. If manual input does not work, it's ok to use other secret names instead. Please be aware that you should replace secrets with the new ones in Action files! [Here](https://docs.github.com/en/actions/reference/encrypted-secrets) you can find detailed secrets using guide. :-)
> 
> Thanks for replying!
> I deleted the older secrets and manually typed `student_id` and `student_id_pwd`. And I set the `student_id` as my student number:18120482 and `student_id_pwd` is my password for logging in the `shu.selfreport` website.
> 
> Should everything be alright now?

Yep, everything should be OK now. 

You must have noticed that there are two Action files in this repo, one is for automated reporting and one is for manual reporting. Please ensure that the automated one is enabled so that the cron job will execute as planned. For the manual one, you can use it to test your secrets by click "Run workflow" button with "master" branch selected. 

As selfreport website may not response correctly, automated actions may not succeed, you can use the manually reporting Action to run the reporting workflow or wait for the next execution to fill in missed reports. 

As the report content may change, use Pull Requests in your repo to sync my modifications if I update these scripts.

**Comment by CaiZhuoyue** [comment]
> > > Yes, what I refer to is repository secrets and they are two different secret items used in Action yml file, which means two secrets need adding to your forked repo.
> > > I've read your issue twice and then found that it's a secrets adding issue, not a parsing issue. lol. I want to ask that did you try not copy these strings but type them manually? As none of my friends have problem in adding these params, I think you may paste the string with characters that not allowed by github's rules, e.g. spaces. If manual input does not work, it's ok to use other secret names instead. Please be aware that you should replace secrets with the new ones in Action files! [Here](https://docs.github.com/en/actions/reference/encrypted-secrets) you can find detailed secrets using guide. :-)
> > 
> > 
> > Thanks for replying!
> > I deleted the older secrets and manually typed `student_id` and `student_id_pwd`. And I set the `student_id` as my student number:18120482 and `student_id_pwd` is my password for logging in the `shu.selfreport` website.
> > Should everything be alright now?
> 
> Yep, everything should be OK now.
> 
> You must have noticed that there are two Action files in this repo, one is for automated reporting and one is for manual reporting. Please ensure that the automated one is enabled so that the cron job will execute as planned. For the manual one, you can use it to test your secrets by click "Run workflow" button with "master" branch selected.
> 
> As selfreport website may not response correctly, automated actions may not succeed, you can use the manually reporting Action to run the reporting workflow or wait for the next execution to fill in missed reports.
> 
> As the report content may change, use Pull Requests in your repo to sync my modifications if I update these scripts.

还是没成功！我在master branch，两个repository secrets也都是对的。

1 每天早上8点和晚上8点并没自动报
2 我在actions里面re-run显示了成功 但是我去每日一报上面看还是没有报

why?????  :(

**Comment by AutoRip** [comment]
Hi @CaiZhuoyue，还麻烦检查一下下面几点。

（1）确保名为Execute check-in based on Github Actions的workflow是启用的。
（2）1月17日每日一报填报内容产生了更新，需要你在forked repo里pull request我仓库中的所有变更以进行代码同步。
（3）还麻烦查看Action中Execute这一步的详细运行状态，正常填报的结果如下图（1月17日晚上开始，每日一报填报内容的更新导致旧代码执行也会显示如下结果，请进行步骤2更新脚本后使用manually脚本手动触发一次填报查看结果）。
（4）当前由于每日一报系统自身问题，历史填报记录中显示体温0°C是正常的，不是本脚本导致的问题。

:-)

![image](https://user-images.githubusercontent.com/22536147/104929519-f603fb80-59de-11eb-8131-4d8a62a56543.png)
